### ISSUE TITLE
ParenMode can't seem to unindent

### ISSUE THREAD

**Issue by GoranM** [oakmac/parinfer-viml#8]
My simple test function:

```viml
function! ParinferTest()
        let buffer_text = join(getline(1, '$'), "\n")

        let result = g:ParinferLib.ParenMode(buffer_text, {})

        " write result text to buffer:
        let lines = split(result.text, "\n")
        let counter = 1
        for line in lines
                call setline(counter, line)
                let counter += 1
        endfor
endfunction
```

Given a buffer with the following text:

```clojure
(def m {:foo 1
             :bar 2
             :baz 3})
```

Calling `ParinferTest()` results in the same thing:

```clojure
(def m {:foo 1
             :bar 2
             :baz 3})
```

I assume it should produce:

```clojure
(def m {:foo 1
        :bar 2
        :baz 3})
```

Since that's how it works in [the demo editor on the official parinfer site](https://shaunlebron.github.io/parinfer/#paren-mode).

**Comment by oakmac** [comment]
The before / after example here is "correct" as far as ParenMode works. The paren structure is in sync with the indentation levels.

**Comment by GoranM** [comment]
In the demo editor, if you start with this:

```clojure
(def my-map {:foo 1
             :bar 2
             :baz 3})
```

And then backspace "my-map" into something shorter, like just "m", the indentation is pulled back to keep everything aligned, and the result is:

```clojure
(def m {:foo 1
        :bar 2
        :baz 3})
```

But that's not how it works in vim, using your implementation of parinfer, so that's why I'm confused.

**Comment by oakmac** [comment]
Both `IndentMode` and `ParenMode` accept a second argument with some options. Off the top of my head, `cursorDx` is the one needed to preserve child indentation in ParenMode. This API reference is relevant: https://github.com/shaunlebron/parinfer/tree/1.8.1/lib#api

Coincidentally, this changed just a few hours ago on the master branch of [parinfer.js](https://github.com/shaunlebron/parinfer/tree/master/lib). It's a pretty substantial change to how Parinfer works (it removes the need for ParenMode in the vast majority of cases). This port is in need of an update to get in sync with parinfer.js

Another thing worth noting: this implementation of Parinfer is very slow due to the fact that VimL is slow. I am not a Vim user myself, but I know that the [Neovim Parinfer plugin](https://github.com/clojure-vim/nvim-parinfer.js/tree/master) uses parinfer.js for speed reasons. Is this something you were just playing around with or are you in the process of making a full VimL extension?

**Comment by GoranM** [comment]
Ah, I see.

I also had to pass `cursorLine` and `cursorX` values in addition to `cursorDx`, and then it seemed to work fine.

I'm surprised that someone who doesn't use vim would write a vim implementation of parinfer, but I'm glad you did it, because I find it quite useful, and more than fast enough for my needs.

Do you plan on updating your port to match the latest parinfer.js changes?

> Is this something you were just playing around with or are you in the process of making a full VimL extension?

I'm using [bhurlow's plug-in](https://github.com/bhurlow/vim-parinfer), which is using your library.

I wrongly assumed that the issue was in your port, and that's what brought me here.

Anyway, thanks for helping me clear this up.
